In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection, preprocessing
import xgboost as xgb

import datetime
from scipy.stats import norm
import pickle
import xgboost as xgb

import numpy as np
from sklearn.model_selection import KFold, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.datasets import load_iris, load_digits, load_boston
from xgboost import XGBRegressor

F:\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
xgb1 = XGBRegressor(
    learning_rate=0.1,
    max_depth=6,
    subsample= 0.6,
    colsample_bytree= 1,
    objective='reg:linear',
    nthread =4,
    seed=317
)
xgb2 = XGBRegressor(
    learning_rate=0.2,
    max_depth=6,
    subsample= 0.7,
    colsample_bytree= 0.7,
    objective= 'reg:linear',
    nthread =4,
    seed=624
)
xgb3 = XGBRegressor(
learning_rate=0.05,
max_depth=5,
subsample= 0.7,
colsample_bytree= 0.7,
objective= 'reg:linear',
nthread =4,
seed=2017
)

In [3]:
class Ensemble(object):
    def __init__(self, n_folds, stacker, base_models):
        self.n_folds = n_folds
        self.stacker = stacker
        self.base_models = base_models
    def fit_predict(self, X, y, T):
        X = np.array(X)
        y = np.array(y)
        T = np.array(T)
        folds = list(KFold(len(y), n_folds=self.n_folds, shuffle=True, random_state=2016))
        S_train = np.zeros((X.shape[0], len(self.base_models)))
        S_test = np.zeros((T.shape[0], len(self.base_models)))
        for i, clf in enumerate(self.base_models):
            S_test_i = np.zeros((T.shape[0], len(folds)))
            for j, (train_idx, test_idx) in enumerate(folds):
                X_train = X[train_idx]
                y_train = y[train_idx]
                X_holdout = X[test_idx]
                # y_holdout = y[test_idx]
                clf.fit(X_train, y_train)
                y_pred = clf.predict(X_holdout)[:]
                S_train[test_idx, i] = y_pred
                S_test_i[:, j] = clf.predict(T)[:]
            S_test[:, i] = S_test_i.mean(1)
        self.stacker.fit(S_train, y)
        y_pred = self.stacker.predict(S_test)[:]
        return y_pred

In [5]:
stacker=XGBRegressor()
base_models = [xgb1,xgb2,xgb3]
ens = Ensemble(5,stacker,base_models)

In [6]:
from sklearn.cross_validation import KFold
train = pd.read_csv('new_train.csv')
test = pd.read_csv('new_test.csv')

train.drop(['id','timestamp'],axis=1,inplace=True)
test.drop(['id','timestamp'],axis=1,inplace=True)
train_y = train['price_doc']
train_x = train.drop(['price_doc'],axis=1)

for c in train_x.columns:
    if train_x[c].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train_x[c].values))
        train_x[c] = lbl.transform(list(train_x[c].values))

for c in test.columns:
    if test[c].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(test[c].values))
        test[c] = lbl.transform(list(test[c].values))

In [8]:
train_x.head()
train_y.head()
test.head()

,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,product_type,...,pts_floor_ratio,gender_ratio,kg_park_ratio,high_ed_extent,pts_x_state,lifesq_x_state,floor_x_state,building_age,room_sq,floor_inverse
0,39.0,20.7,2,9.0,1,1998.0,1.0,8.9,3.0,0,...,0.012682,0.867921,0.038322,9.515225,0.342401,62.1,6.0,17.0,11.80,7.0
1,79.2,NaN,8,17.0,1,NaN,3.0,NaN,1.0,1,...,0.048593,0.884253,0.270927,1.117747,0.826083,NaN,8.0,NaN,NaN,9.0
2,40.5,25.1,3,5.0,2,1960.0,2.0,4.8,2.0,0,...,0.023337,0.813867,0.025994,2.979114,0.233371,50.2,6.0,55.0,10.15,2.0
3,62.8,36.0,17,17.0,1,2016.0,2.0,NaN,3.0,1,...,0.181953,0.901473,0.568177,1.110070,9.279626,108.0,51.0,NaN,NaN,0.0
4,40.0,40.0,17,17.0,1,NaN,1.0,NaN,1.0,1,...,0.037060,0.884253,0.196621,1.374597,0.630014,40.0,17.0,NaN,NaN,0.0

In [9]:
train_x.head()

,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,product_type,...,pts_floor_ratio,gender_ratio,kg_park_ratio,high_ed_extent,pts_x_state,lifesq_x_state,floor_x_state,building_age,room_sq,floor_inverse
0,43.0,27.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,0.885149,0.067498,1.221523,NaN,NaN,NaN,NaN,NaN,NaN
1,34.0,19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,0.812660,0.268308,1.849999,NaN,NaN,NaN,NaN,NaN,NaN
2,43.0,29.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,0.824169,0.130991,3.219286,NaN,NaN,NaN,NaN,NaN,NaN
3,89.0,50.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,0.867661,2.297865,1.317732,NaN,NaN,NaN,NaN,NaN,NaN
4,77.0,77.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,0.922563,0.959783,1.520114,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
test.head()

,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,product_type,...,pts_floor_ratio,gender_ratio,kg_park_ratio,high_ed_extent,pts_x_state,lifesq_x_state,floor_x_state,building_age,room_sq,floor_inverse
0,39.0,20.7,2,9.0,1,1998.0,1.0,8.9,3.0,0,...,0.012682,0.867921,0.038322,9.515225,0.342401,62.1,6.0,17.0,11.80,7.0
1,79.2,NaN,8,17.0,1,NaN,3.0,NaN,1.0,1,...,0.048593,0.884253,0.270927,1.117747,0.826083,NaN,8.0,NaN,NaN,9.0
2,40.5,25.1,3,5.0,2,1960.0,2.0,4.8,2.0,0,...,0.023337,0.813867,0.025994,2.979114,0.233371,50.2,6.0,55.0,10.15,2.0
3,62.8,36.0,17,17.0,1,2016.0,2.0,NaN,3.0,1,...,0.181953,0.901473,0.568177,1.110070,9.279626,108.0,51.0,NaN,NaN,0.0
4,40.0,40.0,17,17.0,1,NaN,1.0,NaN,1.0,1,...,0.037060,0.884253,0.196621,1.374597,0.630014,40.0,17.0,NaN,NaN,0.0

In [11]:
train_y.head()

0    4.986523e+06
1    5.114382e+06
2    4.858663e+06
3    1.116640e+07
4    1.392088e+07
Name: price_doc, dtype: float64

In [13]:
pred = ens.fit_predict(train_x,train_y,test)

In [14]:
xgb4 = XGBRegressor(
    learning_rate=0.01,
    max_depth=7,
    subsample= 0.7,
    colsample_bytree= 1,
    objective='reg:linear',
    nthread =4,
    seed=0
)
xgb5 = XGBRegressor(
    learning_rate=0.3,
    max_depth=5,
    subsample= 0.6,
    colsample_bytree= 0.6,
    objective= 'reg:linear',
    nthread =4,
    seed=2000
)
xgb6 = XGBRegressor(
learning_rate=0.05,
max_depth=6,
subsample= 0.6,
colsample_bytree= 0.6,
objective= 'reg:linear',
nthread =4,
seed=915
)
stacker2 = xgb3
base_models2 = [xgb1,xgb2,xgb6,xgb4,xgb5]
ens2 = Ensemble(10,stacker2,base_models2)
pred2 = ens2.fit_predict(train_x,train_y,test)

In [15]:
pred

array([ 5480130.  ,  8283095.  ,  5647362.5 , ...,  4149128.25,
        4652477.5 ,  8103937.5 ], dtype=float32)

In [16]:
pred2

array([ 5564040.5,  8039764.5,  5579711. , ...,  4323424.5,  4644528.5,
        7527908. ], dtype=float32)

In [17]:
pred.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [19]:
result1 = pd.read_csv('../output/2017_6_26_3.csv')

In [20]:
result1['price_doc'] = pred*0.948

In [21]:
result1.to_csv('../output/2017_6_28_1.csv')

In [22]:
result1.to_csv('../output/2017_6_28_1.csv',index=False)

In [25]:
result1['price_doc'] = pred2*0.948 

#在得到新数据集的时候，因为仿照kernels使用了magic number，对训练集房价乘以了1.054880504
#所以这里只好对结果进行逆变换

result1.to_csv('../output/2017_6_28_2.csv',index=False)